name: Java CI

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build et tests
        run: mvn -f ndarray/pom.xml clean verify

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    permissions:
      packages: write
      contents: read

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Se connecter à GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image Docker
        run: docker build -t ghcr.io/maya1002/ndarray:latest .

      - name: Run container Docker (démo)
        run: docker run ghcr.io/maya1002/ndarray:latest

      - name: Push image sur GitHub Packages
        run: docker push ghcr.io/maya1002/ndarray:latest